# Generated by Django 5.1.1 on 2024-09-27 21:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='based',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
